logging:
  level:
    root: info

server:
  port: 8080

spring:
  jpa:
    show-sql: true

  data:
    mongodb:
      uri: mongodb+srv://admin:P%40ssword01@cluster0-7zpzu.gcp.mongodb.net/test?retryWrites=true&w=majority
      database: yhack
#      host: localhost
#      port: 27017
#      username: username
#      password: password