logging:
  level:
    root: info

server:
  port: 8080

spring:
  jpa:
    show-sql: true

  data:
    mongodb:
      database: yhack
      host: localhost
      port: 27017
#      username: username
#      password: password